### ISSUE TITLE
Switch to extra-data?

### ISSUE THREAD

**Issue by barthalion** [flathub/org.srb2.SRB2#1]
I didn't want to delay the merge; I think that it would be generally fine to fetch the installer and the patch zip via extra-data. The entire process with extracting assets with `p7zip` may be confusing to regular user and I don't think it's accurately documented on upstream website.

**Comment by ghisvail** [comment]
I thought about it too. Do I need to build `p7zip` or is it available in the sdk?

**Comment by barthalion** [comment]
You will need to bundle it.

**Comment by cbm755** [comment]
I've done the bundling, you can grab my p7zip.json at https://github.com/flathub/flathub/pull/1525

Or I'm trying to port it yaml but not working yet...
