### ISSUE TITLE
Commercial assets????

### ISSUE THREAD

**Issue by TiZ-EX1** [flathub/org.srb2.SRB2#2]
Hey, it's awesome to see SRB2 on Flatpak! Thanks for the effort put forth to make this happen.

But I'm really confused about the description on Flathub mentioning that it needs commercial assets and that the website explains more. SRB2 is based on Sonic IP, yes, but as far as I know, it's FOSS from top to bottom, and all the assets were made by the developers. And I can't find anything about these commercial assets on the website.

**Comment by ghisvail** [comment]
> And I can't find anything about these commercial assets on the website

I should have used `proprietary` instead of `commercial`. The assets are in a (very) grey area because of the Sonic IP and I believe upstream is well aware of that based on the wording of the corresponding [README](https://github.com/STJr/SRB2/blob/master/assets/README.txt).

**Comment by ghisvail** [comment]
Once #1 is sorted this won't be an issue and the notice will be removed.

**Comment by ghisvail** [comment]
I have adjusted the description.

**Comment by TiZ-EX1** [comment]
Sonic Team has a very positive attitude about fan games, but in an objective, legal sense, that makes sense. Thanks for your work on this. :)

**Comment by ghisvail** [comment]
I appreciate Sonic Team's kindness towards its fan-made community. But afaik, they did not officially release their IP under a free license, so the Flathub community needs to remain cautious with its redistribution.

I am closing this issues in favor of #1, which is under way.
