### ISSUE TITLE
Copyright infrigment?

### ISSUE THREAD

**Issue by hadess** [flathub/org.srb2.SRB2#4]
I don't think that using Sonic's character design or name without explicit permission from SEGA would be allowed.

**Comment by ghisvail** [comment]
Disclaimer: IANAL, the engine is open source and the regular game assets are derived from proprietary content. We do not redistribute them for this reason, and they can be substituted for other fan-made content if desired.

As for the use of the name "Sonic" in the game title, you may have a point. That being said, there has been a huge amount of fan-made Sonic content produced for the last decade, with [words of encouragement](https://www.destructoid.com/sega-gives-sonic-fans-the-okay-to-make-games-386389.phtml) from the Sonic Team. If this were truly an issue, I believe the community would have been warned long before.

**Comment by hadess** [comment]
I guess that the icon, name and screenshots are all fair use as they relate to the project, and that the project would get notified about possible copyright issues before we would.
