### ISSUE TITLE
Flatpak does not appear to be including 3D models currently

### ISSUE THREAD

**Issue by MugofBro** [flathub/org.srb2.SRB2#46]
Self explanatory, enabling models in the Flatpak version of the application does not appear to be loading them. I tried digging around in the files and I noticed that a models.dat didn't appear to be included, so I'm unsure if that is the cause. I have a bit of limited knowledge when it comes to Flatpak file structure, but hopefully this can help with investigation.

**Comment by riomccloud** [comment]
I'm not able to test for now, but I believe that including these missing files is enough to solve the problem. Could you install the test build in the aforementioned PR and let us know if the issue is resolved?

**Comment by MugofBro** [comment]
Tried installing with the provided terminal command below:

flatpak install --user https://dl.flathub.org/build-repo/28218/org.srb2.SRB2.flatpakref

Unfortunately, this provided the following error. I am running the current stable version of Steam OS on Steam Deck.

Error: While trying to apply extra data: apply_extra script failed, exit status 2816
error: Failed to install org.srb2.SRB2: While trying to apply extra data: apply_extra script failed, exit status 2816

Running the commend with / without "--user" provided the same result. The stable Flatpak installs without issue, so I'm unsure if this is user error on my part
