### ISSUE TITLE
A New update(s) has released (2.2.13) 

### ISSUE THREAD

**Issue by ToastedCheeseYT** [flathub/org.srb2.SRB2#52]
Title is self explanatory.

**Comment by ghisvail** [comment]
Thanks for pinging me. By experience, it's best to wait a bit until the release is confirmed to be stable. They have had corrective releases in the past, and it looks like what happened with versions `2.2.12` and `2.2.13`.

**Comment by violetrepo** [comment]
So when should the new update be expected to drop on the flatpack?

**Comment by ghisvail** [comment]
Le 15 septembre 2023 18:08:13 GMT+02:00, violetrepo ***@***.***> a écrit :
>So when should the new update be expected to drop on the flatpack?
>

Whenever someone submits a PR with an appropriate update of the manifest, and confirms the build works 👍

**Comment by violetrepo** [comment]
@ghisvail a pull request has been made jus letting ya know
