### ISSUE TITLE
srb2-gcc.patch needs to be updated

### ISSUE THREAD

**Issue by violetrepo** [flathub/org.srb2.SRB2#56]
So the app can actually be updated

**Comment by ghisvail** [comment]
What's the problem? What's your platform? Any logs?

There is a basic minimum to provide to open an issue regardless of the project.

I am confused since @riomccloud confirmed he tested the update.

**Comment by violetrepo** [comment]
Yes it was tested but what wasnt tested is updating it from the api of flathub
Which it hasnt appeared on the page yet and I went through the code and saw that the srb2-gcc.patch file doesnt match the metadata files

**Comment by violetrepo** [comment]
That is if I'm understanding stuff correctly which I could jus be wrong

**Comment by ghisvail** [comment]
Just provide your logs for `flatpak install flathub org.srb2.SRB2`.

Assuming the test build [here](https://github.com/flathub/org.srb2.SRB2/pull/53#issuecomment-1721605807) was working, there is no reason why the Flathub version would not. That being said, I did not test the build myself and trusted @riomccloud, who reported it working.

**Comment by violetrepo** [comment]
There are no logs to provide since if you check [[flathub.org/apps/details/org.srb2.SRB2](https://flathub.org/apps/details/org.srb2.SRB2)](url) 
the link provided you will see that the page for srb2 hasnt been updated therefor the update never went through for user end

**Comment by ghisvail** [comment]
The update to the manifest happened 2 hours ago, and according to the Flathub docs:

> The build is published (i.e. signed and imported) into the Flathub Flatpak repo manually (via the web ui) or automatically after 3 hours, and the build will be available to your users.

I believe this is just a matter of patience, really.
