### ISSUE TITLE
Wayland socket should be removed

### ISSUE THREAD

**Issue by katsy** [flathub/org.srb2.SRB2#59]
Wayland support is currently broken, See reports of the issue:

![Screenshot at 2023-09-29 13-00-35](https://github.com/flathub/org.srb2.SRB2/assets/13043950/b2831776-029c-460d-b865-95106e32b015)
![Screenshot at 2023-09-29 13-01-43](https://github.com/flathub/org.srb2.SRB2/assets/13043950/2e1a3db8-ece0-4b98-92c6-8da4394c16d5)

**Comment by bbhtt** [comment]
I can confirm, I see the same issue:

![image](https://github.com/flathub/org.srb2.SRB2/assets/62639087/77c0d4a2-d971-4621-af0a-cc06b730e50c)
