### ISSUE TITLE
Update to 2.2.8

### ISSUE THREAD

**Issue by ElonSatoshi** [flathub/org.srb2.SRB2#8]
It seems like the latest version is 2.2.8: https://www.srb2.org/download/

Edit: Oh wow, it was only released 2 days ago. I'm sure you'll get to it eventually! Thank you for keeping this flatpak up to date!

2nd edit: I've been told on Discord that there may have been some issues with 2.2.8. Perhaps it makes sense to wait a little while in case they release a 2.2.9 shortly for another bugfix?

**Comment by ghisvail** [comment]
> Perhaps it makes sense to wait a little while in case they release a 2.2.9 shortly for another bugfix?

I trust your judgement on that. Feel free to ping me on this thread once 2.2.9 finds its way to a release :+1:

**Comment by ElonSatoshi** [comment]
Well, it wasn't a certain thing. And it's been a few days. Maybe we're going to have 2.2.8 for a while. Also, I just found out that multiplayer doesn't work unless you have the most recent version.

Would you be interested in teaching me how to help maintain this package? I have Element, IRC, Reddit, and Discord for communication, just ask me which one you want to use?

**Comment by ghisvail** [comment]
Le jeu. 8 oct. 2020 à 20:36, ElonSatoshi <notifications@github.com> a
écrit :

> Well, it wasn't a certain thing. And it's been a few days. Maybe we're
> going to have 2.2.8 for a while. Also, I just found out that multiplayer
> doesn't work unless you have the most recent version.
>
Let's work on an update towards 2.2.8 then.

> Would you be interested in teaching me how to help maintain this package?
> I have Element, IRC, Reddit, and Discord for communication, just ask me
> which one you want to use?
>
That's a great idea.

I think you should create a `v2.2.8` branch, update the tag and commit id
in the manifest file and submit a PR. That won't be sufficient, but it will
get us started and provide a dedicated thread for further discussion.

**Comment by ElonSatoshi** [comment]
Alright! How do I "update the tag and commit id
in the manifest file"?

**Comment by ElonSatoshi** [comment]
Alright! I'm working on a commit with some metadata, tag, and checksum changes.

**Comment by ElonSatoshi** [comment]
@ghisvail 

Pull request has been made! https://github.com/flathub/org.srb2.SRB2/pull/9

**Comment by ghisvail** [comment]
> Why does it download the old 2.2.1 installer for srb2-assets?

The base assets stayed at v2.2.1 until v2.2.6. They might need an update for v2.2.8.

**Comment by ghisvail** [comment]
Regarding the apply_extra failure, how did you compute the sha256 sum and archive size in bytes?

**Comment by ElonSatoshi** [comment]
> Regarding the apply_extra failure, how did you compute the sha256 sum and archive size in bytes?

I used `sha256sum` and `du -b` after downloading the archive. What's the proper way to do it?

**Comment by ghisvail** [comment]
That's what I use too. Never seen this apply_extra error before, so we'll
have to investigate a bit.

Le ven. 9 oct. 2020 à 14:30, ElonSatoshi <notifications@github.com> a
écrit :

**Comment by ElonSatoshi** [comment]
**caution: filename not matched:  *.dta**

```
$ flatpak install --user -v https://dl.flathub.org/build-repo/28682/org.srb2.SRB2.flatpakref

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/[scrubbed]/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

F: Opening user flatpak installation at path /home/[scrubbed]/.local/share/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Fetching summary file for remote ‘srb2-origin’
F: Transaction: install srb2-origin:app/org.srb2.SRB2/x86_64/test[*]
F: marking op install:app/org.srb2.SRB2/x86_64/test resolved to 0a0cf1cbabd2dce5182d7b537d0681c39eb10d0a005857a70fc353659bc109f6
F: Updating dependent runtime runtime/org.freedesktop.Platform/x86_64/20.08
F: Transaction: update flathub:runtime/org.freedesktop.Platform/x86_64/20.08[$old]
F: Fetching summary file for remote ‘flathub’
F: marking op update:runtime/org.freedesktop.Platform/x86_64/20.08 resolved to 54fc005a60be576aead95993847430df346c11daf1740efabb8fde39638da84a
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/20.08[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/20.08[/en, /eo, /es]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.openh264/x86_64/2.0[*]
F: marking op install/update:runtime/org.freedesktop.Platform.openh264/x86_64/2.0 resolved to 73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b
F: marking op install/update:runtime/org.freedesktop.Platform.Locale/x86_64/20.08 resolved to 02a02706089975568f19522dd02b2b04e68212fdf6ef6780c2baafabf9a60b02
F: marking op install/update:runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 resolved to 13b663698f585858f14e30f70bbd07b07e3d4825617115e803acd4d4a2ed5795

org.srb2.SRB2 permissions:
    ipc	network	fallback-x11	pulseaudio	wayland	x11	devices



 1.	   	org.srb2.SRB2	x86_64	test	srb2-origin	< 197.3 MB

Proceed with these changes to the user installation? [Y/n]: y
Installing… █▌                     8%  592 bytes/sF: Loading https://github.com/STJr/SRB2/releases/download/SRB2_release_2.2.1/SRB2-v_221-Installer.exe using libsoup
Installing… █████████████████▏    86%  1.1 MB/s  00:23F: Received 163207241 bytes
F: Loading https://github.com/STJr/SRB2/releases/download/SRB2_release_2.2.8/SRB2-v2.2.8-Patch.zip using libsoup
Installing… ████████████████████ 100%  1.1 MB/s  00:00F: Received 29008609 bytes
Installing… ████████████████████ 100%  1.1 MB/s  00:00F: No checksum specified, getting tip of app/org.srb2.SRB2/x86_64/test from origin srb2-origin
F: tip resolved to: 0a0cf1cbabd2dce5182d7b537d0681c39eb10d0a005857a70fc353659bc109f6
F: extracting extra data to /home/[scrubbed]/.local/share/flatpak/app/org.srb2.SRB2/x86_64/test/.0a0cf1cbabd2dce5182d7b537d0681c39eb10d0a005857a70fc353659bc109f6-VQXHS0/files/extra
F: Opening user flatpak installation at path /home/[scrubbed]/.local/share/flatpak
F: Disallowing ipc access
F: Disallowing network access
F: Running /app/bin/apply_extra 
caution: filename not matched:  *.dta
Error: While trying to apply extra data: apply_extra script failed, exit status 2816                   
error: Failed to install org.srb2.SRB2: While trying to apply extra data: apply_extra script failed, exit status 2816
```

**Comment by ghisvail** [comment]
Could you inspect the content of the patch archive ?

Seems like there is now a full archive which means we might be able to get
rid of the installer exe file and p7zip?

Le ven. 9 oct. 2020 à 16:49, ElonSatoshi <notifications@github.com> a
écrit :

**Comment by ElonSatoshi** [comment]
It's the new 2.2.8 patch that doesn't contain any *.dta files:

```
unzip -o ~/Downloads/SRB2-v2.2.8-Patch.zip "*.dta" "*.pk3"
Archive:  /home/[scrubbed]/Downloads/SRB2-v2.2.8-Patch.zip
  inflating: patch.pk3               
  inflating: patch_music.pk3         
caution: filename not matched:  *.dta
```

The question is, is it this error that's actually halting the entire process? The *.pk3 files were extracted without any problem. And why are the *.dta files gone? That last question I will ask the SRB2 discord.

**Comment by santiagocezar** [comment]
The 2.2.8 patch can only be applied to 2.2.6 and .7 versions of the game, and I guess there are no .dta files because they haven't been changed?

Anyway I'd also recommend using the Full archive from the [releases](https://github.com/STJr/SRB2/releases/tag/SRB2_release_2.2.8) or the Installer, as the patch was only meant for current installations of the game

**Comment by ghisvail** [comment]
Let's go for the full archive then 👍

Le ven. 9 oct. 2020 à 20:45, Santiago Cézar <notifications@github.com> a
écrit :

**Comment by CKKGaming** [comment]
I think all you need to do is change SRB2-v2.2.8-Patch to SRB2-v2.2.8-Full. Is there any progress? I would try but I have no idea how to.

**Comment by ghisvail** [comment]
Have a look at #10 once the bot is done building.

**Comment by santiagocezar** [comment]
I've installed it and it seems it's working. I didn't test everything yet but playing online and singleplayer works

**Comment by CKKGaming** [comment]
Thank god. Now I can use the flatpak again.
